### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by lukasbystricky** [dylkol/g-k-chesterton_the-everlasting-man#2]
Sorry, I should have mentioned this earlier, but I have a slight concern about some of the editorial commits where you remove hyphens (specifically fdb3723, e106aad, 810a77b, 20b542e). Was there any specific reason for these commits? 

Typically after running moderinze-spelling we only replace hyphens with a space to get rid of mismatches, although there can be other considerations; for instance if "banna peel" was used, then removing the hyphen in "orange-peel" would make sense. If there's no special reason for these commits, I think they should be dropped. (As a side note, in our corpus there are plenty of cases of [orange-peel](https://github.com/search?q=owner%3Astandardebooks+path%3Asrc%2Fepub%2Ftext%2F*.xhtml+orange-peel&type=code), [paving-stone](https://github.com/search?q=owner%3Astandardebooks+path%3Asrc%2Fepub%2Ftext%2F*.xhtml+paving-stone&type=code) and [prayer-book](https://github.com/search?q=owner%3Astandardebooks+path%3Asrc%2Fepub%2Ftext%2F*.xhtml+prayer-book&type=code), as well as a few cases of non-sequitur and one case of prayer-wheel).

**Comment by dylkol** [comment]
Iirc there were one or two cases where hyphen and non-hyphen spellings were used inconsistently, but for the others I thought I had to follow the Merriam-Webster spelling. I'll go over the latter ones and drop them then!

-------- Oorspronkelijk bericht --------
Op 1 mei 2024 07:36, schreef Lukas Bystricky :

**Comment by lukasbystricky** [comment]
Yeah I made the same mistake a few times. I think this should probably be more clearly spelt out somewhere, but the rule I was told is that we update to the MW spelling if the "modern" version removes the space/hyphen entirely. In other words we don't replace a hyphen with a space.

**Comment by dylkol** [comment]
Alright good to know then, thanks. I think I should have removed all of these cases then, only ones remaining where I either remove the hyphen or add it.

**Comment by lukasbystricky** [comment]
Ok, sorry one (really) final thing: in 647978d you removed the italics around the poem title, but you forgot to add quotes around it.

**Comment by dylkol** [comment]
Ah yeah right... should the quotation marks be inside or outside the span tag? Can't seem to find it in the SEMOS.

**Comment by lukasbystricky** [comment]
Outside is fine.

**Comment by dylkol** [comment]
ok, done then
